name = "ashuftw"
license = "MIT"
licenselink = "https://github.com/nicokaiser/hugo-theme-gallery/blob/main/LICENSE"
description = "A website for my pictures"
homepage = "ashuftw.com"
demosite = "pics.ashuftw.com"
tags = ["gallery", "responsive", "minimal", "dark"]
min_version = "0.123.0"

[author]
  name = "Ashuthosh Shridhar"
  homepage = "https://ashuftw.com"
